#namespace: user-crud-helm

image:
  repository: achugaynov/user-crud
  tag: v1.3

containerPort: 8080

configMap:
  name: app-config

secret:
  name: db-secret
  data:
    dbUser: cG9zdGdyZXM=
    dbPassword: cG9zdGdyZXM=

deployment:
  name: user-app
  replicas: 2
  appLabel: user-app

service:
  name: user-service
  port: 80
  type: ClusterIP

ingress:
  name: user-ingress
  class: nginx
  host1: arch1.homework
  host2: arch1-homework.kalk.pro

postgresqlStorageClass:
  enabled: false

postgresqlPvPvc:
  enabled: true

postgresql:
  enabled: true
  image:
    tag: "16"
  auth:
    username: "postgres"
    password: "postgres"
    database: "appdb"
  storageClass: "standard"
  size: 100Mi
  primary:
    podSecurityContext:
      enabled: true
      fsGroup: 1001  # Owner data group
    containerSecurityContext:
      enabled: true
      runAsUser: 1001  # Container user group

