apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: user-crud
spec:
  template:
    spec:
      containers:
        - name: migration
          image: achugaynov/user-crud:v1.0
          command:
            - sh
            - -c
            - |
              psql -h db-postgresql.pqsql.svc.cluster.local \
                   -U $(DB_USER) \
                   -d db_user_crud \
                   -f migrations/initial.sql
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 1