apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: user-crud
spec:
  containers:
    - name: debug-container
      image: achugaynov/user-crud:v1.0
      command: ["sleep", "3600"]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
  restartPolicy: Never