apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data   # Potentially must be created manually with 0777 access rights
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-db-postgresql-0
  namespace: pqsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: postgres-pv