global:
  postgresql:
    auth:
      username: postgres
      password: postgres
      database: appdb
persistence:
  enabled: true
  storageClass: "standard"
  size: 100Mi
  primary:
    podSecurityContext:
      enabled: true
      fsGroup: 1001  # Owner data group
    containerSecurityContext:
      enabled: true
      runAsUser: 1001  # Container user group
volumePermissions:
    enabled: true
primary:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
readReplicas:
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

