apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.data.dbUser }}
  DB_PASSWORD: {{ .Values.secret.data.dbPassword }}

