{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-db-postgresql-0
  namespace: {{ .Values.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: ""
  volumeName: {{ .Values.persistence.volumeName }}
{{- end }}
